use springbatch;

desc BATCH_JOB_INSTANCE;
desc BATCH_JOB_EXECUTION;
desc BATCH_JOB_EXECUTION_PARAMS;
desc BATCH_JOB_EXECUTION_CONTEXT;

desc BATCH_STEP_EXECUTION;
desc BATCH_STEP_EXECUTION_CONTEXT;

show tables;

select * from BATCH_JOB_INSTANCE;
select * from BATCH_JOB_EXECUTION;
select * from BATCH_JOB_EXECUTION_PARAMS;
select * from BATCH_JOB_EXECUTION_CONTEXT;

select * from BATCH_STEP_EXECUTION;
select * from BATCH_STEP_EXECUTION_CONTEXT;
